# Generated by Django 5.2.1 on 2025-06-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Toy', 'Toy'), ('Furniture', 'Furniture'), ('Automobile', 'Automobile'), ('Book', 'Book'), ('Misc', 'Misc')], max_length=64, null=True),
        ),
    ]
