# Generated by Django 5.2.1 on 2025-06-03 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_lister_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
