# Generated by Django 5.2.1 on 2025-06-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_category_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.bid'),
        ),
    ]
