# Generated by Django 5.2.1 on 2025-06-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='bid',
        ),
    ]
