# Generated by Django 5.2.1 on 2025-06-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('----', '----'), ('Home', 'Home'), ('Toy', 'Toy'), ('Furniture', 'Furniture'), ('Automobile', 'Automobile'), ('Book', 'Book'), ('Misc', 'Misc')], max_length=64, null=True),
        ),
    ]
