# Generated by Django 5.2.1 on 2025-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('----', '----'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Kitchen', 'Kitchen'), ('Food', 'Food'), ('Beverage', 'Beverage'), ('Agriculture', 'Agriculture'), ('Plant', 'Plant'), ('Pet', 'Pet'), ('Medical', 'Medical'), ('Detergents', 'Detergents'), ('Furniture', 'Furniture'), ('Automobile', 'Automobile'), ('Book', 'Book'), ('Misc', 'Misc')], max_length=64, null=True),
        ),
    ]
