# Generated by Django 5.2.1 on 2025-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image4_product_image5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_250',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_500',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(default=dict),
        ),
    ]
