# Generated by Django 5.2.1 on 2025-08-24 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_price_250_remove_product_price_500_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
